version: "3"

services:
  vpn4:
    image: qmcgaw/gluetun
    container_name: vpn4
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US East
    ports:
      - 5904:5900

  vpn5:
    image: qmcgaw/gluetun
    container_name: vpn5
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US East
    ports:
      - 5905:5900

  vpn6:
    image: qmcgaw/gluetun
    container_name: vpn6
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US East
    ports:
      - 5906:5900

  b4:
    image: ayyouboss0011/chrome700x700
    container_name: b4
    network_mode: service:vpn4
    restart: always
    depends_on:
      - vpn4

  b5:
    image: ayyouboss0011/chrome700x700
    container_name: b5
    network_mode: service:vpn5
    restart: always
    depends_on:
      - vpn5

  b6:
    image: ayyouboss0011/chrome700x700
    container_name: b6
    network_mode: service:vpn6
    restart: always
    depends_on:
      - vpn6