version: "3"
services:
  vpn1:
    image: qmcgaw/gluetun
    container_name: vpn1
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US East
    ports:
      - 5901:5900

  vpn2:
    image: qmcgaw/gluetun
    container_name: vpn2
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US East
    ports:
      - 5902:5900

  vpn3:
    image: qmcgaw/gluetun
    container_name: vpn3
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US East
    ports:
      - 5903:5900


  b1:
    image: ayyouboss0011/chrome700x700
    container_name: b1
    network_mode: service:vpn1
    restart: always
    depends_on:
      - vpn1

  b2:
    image: ayyouboss0011/chrome700x700
    container_name: b2
    network_mode: service:vpn2
    restart: always
    depends_on:
      - vpn2

  b3:
    image: ayyouboss0011/chrome700x700
    container_name: b3
    network_mode: service:vpn3
    restart: always
    depends_on:
      - vpn3