version: "3"

services:
  vpn46:
    image: qmcgaw/gluetun
    container_name: vpn46
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US West
    ports:
      - 5946:5900

  vpn47:
    image: qmcgaw/gluetun
    container_name: vpn47
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US West
    ports:
      - 5947:5900

  vpn48:
    image: qmcgaw/gluetun
    container_name: vpn48
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4JZYd2ElHU6lHI8BQ/kdDAAQzYGiL1JAX7qcsOLrrFM=
      - WIREGUARD_ADDRESSES=100.95.37.94/32
      - WIREGUARD_PRESHARED_KEY=m7pGiKXWGmJmopkBsfVZZRu/DlE8lsqc1S2M8DnaAfw=
      - SERVER_REGIONS=US West
    ports:
      - 5948:5900

  b46:
    image: ayyouboss0011/chrome700x700
    container_name: b46
    network_mode: service:vpn46
    restart: always
    depends_on:
      - vpn46

  b47:
    image: ayyouboss0011/chrome700x700
    container_name: b47
    network_mode: service:vpn47
    restart: always
    depends_on:
      - vpn47

  b48:
    image: ayyouboss0011/chrome700x700
    container_name: b48
    network_mode: service:vpn48
    restart: always
    depends_on:
      - vpn48
