version: "3"

services:
  vpn31:
    image: qmcgaw/gluetun
    container_name: vpn31
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.31/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5931:5900"

  vpn32:
    image: qmcgaw/gluetun
    container_name: vpn32
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.32/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5932:5900"

  vpn33:
    image: qmcgaw/gluetun
    container_name: vpn33
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.33/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5933:5900"

  b31:
    image: ayyouboss0011/chrome
    container_name: b31
    network_mode: service:vpn31
    restart: always
    depends_on:
      - vpn31

  b32:
    image: ayyouboss0011/chrome
    container_name: b32
    network_mode: service:vpn32
    restart: always
    depends_on:
      - vpn32

  b33:
    image: ayyouboss0011/chrome
    container_name: b33
    network_mode: service:vpn33
    restart: always
    depends_on:
      - vpn33

