version: "3"

services:
  vpn16:
    image: qmcgaw/gluetun
    container_name: vpn16
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.16/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5916:5900"

  vpn17:
    image: qmcgaw/gluetun
    container_name: vpn17
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.17/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5917:5900"

  vpn18:
    image: qmcgaw/gluetun
    container_name: vpn18
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.18/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5918:5900"

  b16:
    image: ayyouboss0011/chrome
    container_name: b16
    network_mode: service:vpn16
    restart: always
    depends_on:
      - vpn16

  b17:
    image: ayyouboss0011/chrome
    container_name: b17
    network_mode: service:vpn17
    restart: always
    depends_on:
      - vpn17

  b18:
    image: ayyouboss0011/chrome
    container_name: b18
    network_mode: service:vpn18
    restart: always
    depends_on:
      - vpn18

