version: "3"

services:
  vpn13:
    image: qmcgaw/gluetun
    container_name: vpn13
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.13/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5913:5900"

  vpn14:
    image: qmcgaw/gluetun
    container_name: vpn14
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.14/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5914:5900"

  vpn15:
    image: qmcgaw/gluetun
    container_name: vpn15
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.15/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5915:5900"

  b13:
    image: ayyouboss0011/chrome
    container_name: b13
    network_mode: service:vpn13
    restart: always
    depends_on:
      - vpn13

  b14:
    image: ayyouboss0011/chrome
    container_name: b14
    network_mode: service:vpn14
    restart: always
    depends_on:
      - vpn14

  b15:
    image: ayyouboss0011/chrome
    container_name: b15
    network_mode: service:vpn15
    restart: always
    depends_on:
      - vpn15

