version: "3"

services:
  vpn19:
    image: qmcgaw/gluetun
    container_name: vpn19
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.19/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5919:5900"

  vpn20:
    image: qmcgaw/gluetun
    container_name: vpn20
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.20/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5920:5900"

  vpn21:
    image: qmcgaw/gluetun
    container_name: vpn21
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.21/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5921:5900"

  b19:
    image: ayyouboss0011/chrome
    container_name: b19
    network_mode: service:vpn19
    restart: always
    depends_on:
      - vpn19

  b20:
    image: ayyouboss0011/chrome
    container_name: b20
    network_mode: service:vpn20
    restart: always
    depends_on:
      - vpn20

  b21:
    image: ayyouboss0011/chrome
    container_name: b21
    network_mode: service:vpn21
    restart: always
    depends_on:
      - vpn21

