version: "3"

services:
  vpn7:
    image: qmcgaw/gluetun
    container_name: vpn7
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.7/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5907:5900"

  vpn8:
    image: qmcgaw/gluetun
    container_name: vpn8
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.8/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5908:5900"

  vpn9:
    image: qmcgaw/gluetun
    container_name: vpn9
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.9/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5909:5900"

  b7:
    image: ayyouboss0011/chrome
    container_name: b7
    network_mode: service:vpn7
    restart: always
    depends_on:
      - vpn7

  b8:
    image: ayyouboss0011/chrome
    container_name: b8
    network_mode: service:vpn8
    restart: always
    depends_on:
      - vpn8

  b9:
    image: ayyouboss0011/chrome
    container_name: b9
    network_mode: service:vpn9
    restart: always
    depends_on:
      - vpn9

