version: "3"

services:
  vpn34:
    image: qmcgaw/gluetun
    container_name: vpn34
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.34/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5934:5900"
      
  vpn35:
    image: qmcgaw/gluetun
    container_name: vpn35
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.35/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5935:5900"

  vpn36:
    image: qmcgaw/gluetun
    container_name: vpn36
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.36/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5936:5900"

  b34:
    image: ayyouboss0011/chrome
    container_name: b34
    network_mode: service:vpn34
    restart: always
    depends_on:
      - vpn34

  b35:
    image: ayyouboss0011/chrome
    container_name: b35
    network_mode: service:vpn35
    restart: always
    depends_on:
      - vpn35

  b36:
    image: ayyouboss0011/chrome
    container_name: b36
    network_mode: service:vpn36
    restart: always
    depends_on:
      - vpn36

