version: "3"

services:
  vpn22:
    image: qmcgaw/gluetun
    container_name: vpn22
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.22/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5922:5900"

  vpn23:
    image: qmcgaw/gluetun
    container_name: vpn23
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.23/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5923:5900"
      
  vpn24:
    image: qmcgaw/gluetun
    container_name: vpn24
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=+MXVbzRDJmO8VUere5Xtm1Xbf7bpjsl8+sfD3AiLjkI=
      - WIREGUARD_ADDRESSES=10.14.0.24/16
      - SERVER_COUNTRIES=United States
    ports:
      - "5924:5900"

  b22:
    image: ayyouboss0011/chrome
    container_name: b22
    network_mode: service:vpn22
    restart: always
    depends_on:
      - vpn22

  b23:
    image: ayyouboss0011/chrome
    container_name: b23
    network_mode: service:vpn23
    restart: always
    depends_on:
      - vpn23

  b24:
    image: ayyouboss0011/chrome
    container_name: b24
    network_mode: service:vpn24
    restart: always
    depends_on:
      - vpn24

